const axios = require('axios');

const TRELLO_BASE_URL = 'https://api.trello.com/1';

/**
 * Trello API wrapper for SyncBoard
 */
class TrelloService {
  constructor() {
    this.apiKey = process.env.TRELLO_API_KEY;
    this.token = process.env.TRELLO_TOKEN;
    this.defaultBoardId = process.env.TRELLO_BOARD_ID;
    
    if (!this.apiKey || !this.token) {
      console.warn('[Trello] API credentials not configured');
    }
  }
  
  /**
   * Make authenticated request to Trello API
   */
  async request(method, endpoint, data = {}) {
    const url = `${TRELLO_BASE_URL}${endpoint}`;
    // Always send key, token and all data as query params (Trello standard)
    const params = {
      key: this.apiKey,
      token: this.token,
      ...data
    };

    try {
      console.log(`[Trello] ${method} ${endpoint} | idList: ${data.idList || 'N/A'}`);
      const response = await axios({
        method,
        url,
        params // send everything as query params for all request types
      });
      return response.data;
    } catch (error) {
      console.error(`[Trello] API error: ${error.response?.data || error.message}`);
      throw new Error(`Trello API error: ${error.response?.data?.message || error.message}`);
    }
  }
  
  /**
   * Get all boards accessible by the user
   */
  async getBoards() {
    return this.request('GET', '/members/me/boards', {
      fields: 'name,id,url,closed'
    });
  }
  
  /**
   * Get lists on a board
   */
  async getLists(boardId = this.defaultBoardId) {
    return this.request('GET', `/boards/${boardId}/lists`, {
      fields: 'name,id,closed'
    });
  }
  
  /**
   * Get board members for assignment
   */
  async getBoardMembers(boardId = this.defaultBoardId) {
    return this.request('GET', `/boards/${boardId}/members`, {
      fields: 'fullName,username,id'
    });
  }
  
  /**
   * Get available labels on a board
   */
  async getLabels(boardId = this.defaultBoardId) {
    return this.request('GET', `/boards/${boardId}/labels`, {
      fields: 'name,color,id'
    });
  }
  
  /**
   * Create a new card on Trello
   * @param {Object} ticket - Ticket data from SyncBoard
   * @param {string} listId - Target list ID
   */
  async createCard(ticket, listId, boardId) {
    const cardData = {
      name: ticket.title || ticket.task,
      desc: this.formatDescription(ticket),
      idList: listId,
      pos: 'bottom'
    };

    // Add due date if available
    if (ticket.deadline) {
      cardData.due = ticket.deadline;
    }

    // Create the card
    const card = await this.request('POST', '/cards', cardData);
    console.log(`[Trello] Card created: ${card.id} - ${card.name}`);

    // Add labels if specified
    if (ticket.labels && ticket.labels.length > 0) {
      await this.addLabelsToCard(card.id, ticket.labels, boardId);
    }

    // Assign member if specified
    if (ticket.assigneeId) {
      await this.addMemberToCard(card.id, ticket.assigneeId);
    }

    return card;
  }
  
  /**
   * Format ticket description for Trello card
   */
  formatDescription(ticket) {
    let desc = '';
    
    if (ticket.userStory?.story) {
      desc += `## User Story\n${ticket.userStory.story}\n\n`;
    }
    
    if (ticket.description) {
      desc += `## Description\n${ticket.description}\n\n`;
    }
    
    if (ticket.context) {
      desc += `## Context\n${ticket.context}\n\n`;
    }
    
    if (ticket.userStory?.acceptance_criteria) {
      desc += `## Acceptance Criteria\n`;
      ticket.userStory.acceptance_criteria.forEach(ac => {
        desc += `- [ ] ${ac}\n`;
      });
      desc += '\n';
    }
    
    if (ticket.priority) {
      desc += `**Priority:** ${ticket.priority.toUpperCase()}\n`;
    }
    
    if (ticket.deadlineRaw) {
      desc += `**Original deadline:** ${ticket.deadlineRaw}\n`;
    }
    
    desc += `\n---\n*Generated by SyncBoard*`;
    
    return desc;
  }
  
  /**
   * Add labels to a card
   */
  async addLabelsToCard(cardId, labelNames, boardId) {
    const boardLabels = await this.getLabels(boardId);
    
    for (const labelName of labelNames) {
      const label = boardLabels.find(
        l => l.name.toLowerCase() === labelName.toLowerCase()
      );
      
      if (label) {
        await this.request('POST', `/cards/${cardId}/idLabels`, {
          value: label.id
        });
      } else {
        console.warn(`[Trello] Label not found: ${labelName}`);
      }
    }
  }
  
  /**
   * Add member to a card
   */
  async addMemberToCard(cardId, memberId) {
    return this.request('POST', `/cards/${cardId}/idMembers`, {
      value: memberId
    });
  }
  
  /**
   * Match assignee name to board member
   */
  async matchAssignee(assigneeName, boardId = this.defaultBoardId) {
    if (!assigneeName) return null;
    
    const members = await this.getBoardMembers(boardId);
    const normalizedName = assigneeName.toLowerCase();
    
    // Try exact match first
    let match = members.find(
      m => m.fullName.toLowerCase() === normalizedName ||
           m.username.toLowerCase() === normalizedName
    );
    
    // Try partial match
    if (!match) {
      match = members.find(
        m => m.fullName.toLowerCase().includes(normalizedName) ||
             normalizedName.includes(m.fullName.toLowerCase().split(' ')[0])
      );
    }
    
    return match ? match.id : null;
  }
  
  /**
   * Bulk create cards from tickets
   * @param {Array} tickets - Array of ticket objects
   * @param {string} listId - Target list ID
   * @param {string} boardId - Board ID for member matching
   */
  async bulkCreateCards(tickets, listId, boardId) {
    const results = {
      created: [],
      failed: []
    };

    for (const ticket of tickets) {
      try {
        // Try to match assignee
        if (ticket.assignee) {
          ticket.assigneeId = await this.matchAssignee(ticket.assignee, boardId);
        }
        
        const card = await this.createCard(ticket, listId, boardId);
        results.created.push({
          ticketId: ticket.id,
          cardId: card.id,
          cardUrl: card.url
        });
        
        // Rate limiting - Trello API limit is 100 requests per 10 seconds
        await new Promise(resolve => setTimeout(resolve, 100));
      } catch (error) {
        results.failed.push({
          ticketId: ticket.id,
          error: error.message
        });
      }
    }
    
    return results;
  }
  
  /**
   * Verify connection and permissions
   */
  async verifyConnection() {
    try {
      const boards = await this.getBoards();
      return {
        connected: true,
        boardCount: boards.filter(b => !b.closed).length
      };
    } catch (error) {
      return {
        connected: false,
        error: error.message
      };
    }
  }
}

module.exports = new TrelloService();
